---
title: "Lab 1"
author: "44"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE}
sumdiag <- function(A){
  s <- c()
  for (row in 1:min(dim(A)))
    s <- c(s, sum(A[row, ])+sum(A[, row]))-A[row, row]
  diag(s)
}

A <- matrix(c(0, 1, 2, 3, 0,4, 5, 6, 0), nrow = 3)
A <- matrix(1:9, nrow = 3, ncol = 3)
print(sumdiag(A))
```

```{r}
skc <- function(n){
  digits <- as.numeric(unlist(strsplit(as.character(n), "")))
  sum(digits**2)
}

for (N in 1:99){
  while (N!=1 & N!=4)
    N <- skc(N)
}
print(N)
```

```{r}
library(dplyr)
zakupy = read.csv2('zakupy2.csv', header=TRUE)
any(is.na(zakupy))
head(zakupy)
colnames(zakupy)
zakupy_mean <- mean(zakupy$Wydatek)
zakupy_mean
zakupy_sd <- sd(zakupy$Wydatek)
zakupy_sd
wiek_produkcyjny <- filter(zakupy, (PLEC == 'M' & WIEK <=65)|(PLEC == 'K' & WIEK <=68))
wiek_produkcyjny
wiek_emerytalny <- filter(zakupy, (PLEC == 'M' & WIEK >65)|(PLEC == 'K' & WIEK >68))
wiek_emerytalny
```

```{r}
library(readxl)
df <- read_excel('Wyksz_Zarobki.xls')
srednie_wartosci_zarobkow <- c(0, seq(500, 10000, by=1000), 15000)
srednie_wartosci_zarobkow
df_mean <- mean(srednie_wartosci_zarobkow[df$Zarobki])
df_mean
```
