---
title: "Średnie i test losowości"
author: "Adam Michalski"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = TRUE)
```

```{r}
library(DescTools)
wzrost <- read.csv2('wzrost.csv', header=FALSE)
colnames(wzrost) <- c('dane')
quantile(wzrost$dane, probs =c(0.25, 0.5, 0.75))
mean(wzrost$dane)
t.test(wzrost$dane, conf.level = 0.9)
var(wzrost$dane)
VarCI(wzrost$dane, method = "classic", conf.level = 0.9, sides = "two.sided")
```

```{r}
formula1 <- read.csv2('Formula1.csv', header=FALSE)
colnames(formula1) <- c('dane')
n <- length(formula1$dane)
average_speed <- n/(sum(1/formula1$dane))
average_speed
```

```{r}
kosci <- read.csv2('Kosci.csv', header=FALSE)
colnames(kosci) <- c('dane')
n <- length(kosci$dane)
naive_average <- sum(kosci$dane)/n
naive_average
average_dimention <- (sum(kosci$dane^3)/n)^(1/3)
average_dimention
difference <- average_dimention-naive_average
difference
kosci_sd <- (sd(kosci$dane^3))^(1/3)
kosci_sd
average_used_amber <- average_dimention^3
average_used_amber
```

```{r}
library(readxl)
df <- read_excel('Wyksz_Zarobki.xls')
srednie_wartosci_zarobkow <- c(0, seq(500, 10000, by=1000), 15000)
srednie_wartosci_zarobkow
df_median <- quantile(srednie_wartosci_zarobkow[df$Zarobki], probs =c(0.5))
df_median
```

```{r}
pu_test <- function(n, mu, sigma, level){
  normal_sample <- rnorm(n, mu, sigma)
  test_value <- t.test(normal_sample, alternative = "two.sided", mu = mu, conf.level = level)
  if (test_value$conf.int[1] <= mu & mu <= test_value$conf.int[2])
    TRUE
  else
    FALSE
}
eksperyment <- replicate(1000, pu_test(100, 0, 1, 0.9))
ilosc_poprawnych_wyników <- sum(eksperyment)
ilosc_poprawnych_wyników
```