---
title: "Regresja liniowa"
author: "Adam Michalski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ogolna regresja rat}
purchases <- read.csv2('Raty.csv', header = TRUE)
installments <- factor(purchases$Raty, levels = c("N", "T"))
data_0 <- subset(purchases, installments == "N")
data_1 <- subset(purchases, installments == "T")
reg_0 <- lm(Wydatek ~ Dochody, data = data_0)
summary(reg_0)
reg_1 <- lm(Wydatek ~ Dochody, data = data_1)
summary(reg_1)

shapiro.test(reg_0$residuals)
shapiro.test(reg_1$residuals)
```

```{r wykres}
plot(purchases$Dochody, purchases$Wydatek,
     col = ifelse(installments == "T", "blue", "red"),
     pch = 16,
     xlab = "Dochody",
     ylab = "Wydatek",
     main = "Wykres danych wraz z liniami regresji dowolnych modeli")
legend("bottomright", 
       legend = c("Dane z ratami", "Dane bez rat", "Regresja z ratami", "Regresja bez rat"),
       col = c("blue", "red", "blue", "red"),
       pch = c(16, 16, NA, NA, NA),
       lty = c(NA, NA, 1, 1, 1), 
       lwd = c(NA, NA, 2, 2, 2), 
       bty = "n")

range_x = data.frame(Dochody = c(min(purchases$Dochody), max(purchases$Dochody)))
#range_installments <- data.frame(Dochody = rep(range_x$Dochody, 2), 
#                                 installments = rep(c("N", "T"), each = nrow(range_x)))
#lines(range_installments$Dochody, predict(general_model, range_installments), lwd = 2, col = "green")
lines(range_x$Dochody, predict(reg_0, range_x), lwd = 2, col = "red")
lines(range_x$Dochody, predict(reg_1, range_x), lwd = 2, col = "blue")
```

```{r rownolegla regresja rat}
slope <- mean(coef(reg_0)["Dochody"], coef(reg_1)["Dochody"])
adjusted_wydatek_0 <- data_0$Wydatek - slope * data_0$Dochody
intercept_0 <- coef(lm(adjusted_wydatek_0 ~ 1))
intercept_0
adjusted_wydatek_1 <- data_1$Wydatek - slope * data_1$Dochody
intercept_1 <- coef(lm(adjusted_wydatek_1 ~ 1))
intercept_1
```

```{r wykres rownoleglych}
plot(purchases$Dochody, purchases$Wydatek,
     col = ifelse(installments == "T", "blue", "red"),
     pch = 16,
     xlab = "Dochody",
     ylab = "Wydatek",
     main = "Wykres danych wraz z liniami regresji równoległych modeli")
legend("bottomright", 
       legend = c("Dane z ratami", "Dane bez rat", "Regresja z ratami", "Regresja bez rat"),
       col = c("blue", "red", "blue", "red"),
       pch = c(16, 16, NA, NA, NA),
       lty = c(NA, NA, 1, 1, 1), 
       lwd = c(NA, NA, 2, 2, 2), 
       bty = "n")

range_x = data.frame(Dochody = c(min(purchases$Dochody), max(purchases$Dochody)))
lines(range_x$Dochody, slope * range_x$Dochody + intercept_0, lwd = 2, col = "red")
lines(range_x$Dochody, slope * range_x$Dochody + intercept_1, lwd = 2, col = "blue")
```


```{r proba porownania modeli testem anova}
parallel_model<- lm(Wydatek ~ Dochody + installments, data = purchases)
summary(parallel_model)
general_model <- lm(Wydatek ~ Dochody * installments, data = purchases)
summary(general_model)
anova(parallel_model, general_model)
```

```{r model liniowy}
reg_doch_wiek <- lm(Wydatek ~ Dochody + Wiek, data = purchases)
summary(reg_doch_wiek)
shapiro.test(reg_doch_wiek$residuals)
```


```{r wykres 3d}
range_x = seq(min(purchases$Dochody), max(purchases$Dochody), length.out = 5)
range_y = seq(min(purchases$Wiek), max(purchases$Wiek), length.out = 5)
model = function(x, y) reg_doch_wiek$coef[1] + x * reg_doch_wiek$coef[2] + y * reg_doch_wiek$coef[3]
range_z = outer(range_x, range_y, model)
wykres = persp(x = range_x, y = range_y, z = range_z, xlab = "Dochody", ylab = "Wiek", 
               zlab = "Wydatek", ticktype = "detailed", theta = -50, phi = 30,
               cex.axis = 0.7)
points(trans3d(purchases$Dochody, purchases$Wiek, purchases$Wydatek, wykres), col="red", lwd = 2, pch = 10)
segments(trans3d(purchases$Dochody, purchases$Wiek, purchases$Wydatek, wykres)$x, 
         trans3d(purchases$Dochody, purchases$Wiek, purchases$Wydatek, wykres)$y,
         trans3d(purchases$Dochody, purchases$Wiek, predict(reg_doch_wiek), wykres)$x,
         trans3d(purchases$Dochody, purchases$Wiek, predict(reg_doch_wiek), wykres)$y)
```